### ISSUE TITLE
TargetPercent seems short

### ISSUE THREAD

**Issue by RelentlessResults** [pguso/jquery-plugin-circliful#107]
Adding a targetPercent value of 100% doesn't make a complete circle. The following two partial-circles match up:
`
.circliful({ percent: 82.5, targetPercent: 100 });
`

**Comment by silvaigor** [comment]
I have the same problem.

![image](https://cloud.githubusercontent.com/assets/12085539/18999161/14da868c-8734-11e6-8f52-0775567ef929.png)

**Comment by dassaffe** [comment]
Same here.

**Comment by jmvandeel** [comment]
It took me some time to realize this and i believe this should be the case. I have percentage:90 and targetPercentage:90. Both circles should be the same.

**Comment by jmvandeel** [comment]
Dont ask why, but I was able to resolve this by changing the value 360 into 437 on line 109 of the JS file: 
`elements += '<circle cx="100" cy="100" r="69" fill="none" stroke="' + settings.targetColor + '" stroke-width="3" stroke-dasharray="' + (**437** / 100 * settings.targetPercent) + ', 20000" transform="rotate(-90,100,100)" />';`
