### ISSUE TITLE
Centring the percentage text

### ISSUE THREAD

**Issue by atefBB** [pguso/jquery-plugin-circliful#108]
Hi, Thank you for this plugin (it save my day !), I can't centralize the percentage text, how to do it?

**Comment by bronzer-eagle** [comment]
me to

**Comment by atefBB** [comment]
Go to line 48 in jquery.circliful.js file and modify those values :
```
var iconX = 100;
var textY = 115;
var textX = 100;
```
It centralize it for me.

**Comment by atefBB** [comment]
actually the line 49 : 
`var textY = 100;`

**Comment by bronzer-eagle** [comment]
Thanks, hope the author will create changeable props for it

**Comment by atefBB** [comment]
I hope ! but is that a recurrent "error"? should we send a "pull request" or smthg?

**Comment by p0m1d0rka** [comment]
Ty for this method

**Comment by atefBB** [comment]
Actually there is a pull request for that : https://github.com/pguso/jquery-plugin-circliful/pull/102.
