### ISSUE TITLE
data-text not breaking lines

### ISSUE THREAD

**Issue by pcout** [pguso/jquery-plugin-circliful#11]
How do i break lines in data-text ? Is it possible to have two or three lines of text depending on the lenght of the string ?

**Comment by PanRu** [comment]
+1

**Comment by PanRu** [comment]
Just using a stupid way to solve this problem.
Set a fix width to the circle-info class to let it break lines.
like #myStat0 .circle-info {width: 100px; }

**Comment by jimmyt2003** [comment]
+1
