### ISSUE TITLE
Assign data from HTML?

### ISSUE THREAD

**Issue by theunreal** [pguso/jquery-plugin-circliful#110]
Why the percent are not applied in this case?

`<div id="circle" data-percent="100"></div>`

**Comment by hellorich** [comment]
The use of data-attributes has been removed from the script as far as I can tell, which is a shame as it allows to be more easily tied into back end systems.

You can however add this functionality back in your self by using some JavaScript code like so:
```
var animationStep = $('.chart').data('animationStep'),
    percent       = $('.chart').data('percent');

  $( document ).ready(function() {
    $('.chart').circliful({
      animationStep: animationStep,
      percent: percent
    });
  });
```
where your HTML would be:

`<div class="chart" data-animation-step="15" data-percent="82"></div>
`
Obviously follow this pattern for any other options you want to expose to the JavaScript from the HTML.

**Comment by pguso** [comment]
I readded the feature for assign the settings by data attributes.

@hellorich I really dont like hearing that its a shame, i completly rewrote the plugin and forgot to implement this feature again. I spended a lot of time over the years of my free time to offer this plugin. I am always open for improvments and everyone is open to add issues.

**Comment by theunreal** [comment]
@pguso oh cool. thanks! Have you though about changing the style to the old one? It looked pretty good, I still use it on my old website!

![image](https://cloud.githubusercontent.com/assets/6171883/19124404/bdd5af4a-8b3b-11e6-871d-84996890429f.png)

**Comment by pguso** [comment]
@theunreal yes thats a good idea yould you open a new issue please?

**Comment by theunreal** [comment]
@pguso Sure https://github.com/pguso/jquery-plugin-circliful/issues/113
