### ISSUE TITLE
Custom image instead of icon

### ISSUE THREAD

**Issue by theunreal** [pguso/jquery-plugin-circliful#115]
Could be very nice if an option to link custom image instead of a limited font-awesome icon.

**Comment by sgrasso** [comment]
This may not be a feature but can easily be accomplished using just a simple CSS background with positioning on the SVG graphic.   

First you can set the icon position without an icon or any other icon option to remove everything from the center leaving it blank. Also, make sure you remove any fillColor that is being set.
``` js
iconPosition: 'middle',
fillColor: '#eee' //Remove
```
Then try something like this for your custom image.
``` css
#myCircle > svg { 
    background:url(/assets/img/custom_image.png);
    background-position-x: 60px;
    background-position-y: 60px;
    background-repeat: no-repeat;
```
