### ISSUE TITLE
animateInView not working

### ISSUE THREAD

**Issue by kylefraser** [pguso/jquery-plugin-circliful#117]
Does the animateInView not work?

`$( document ).ready(function() {
    $("#circle2").circliful({
      animation: 1,
      animateInView: true,
      animationStep: 1,
      foregroundColor: '#26a69a',
      foregroundBorderWidth: 5,
      backgroundBorderWidth: 5,
      percent: 100,
      replacePercentageByText: "100%",
      text: "Test",
      textStyle: 'font-size: 5px; text-align: center;',
      textColor: '#666',
    });
});`

**Comment by Committing** [comment]
What doesn't work for you? For me the circles will not animate on pageload if circles are in view.

Needs to check if circles are within viewport on page load rather than the scroll event only.

**Comment by kylefraser** [comment]
I get nothing whether it's in view during page load or on a scroll event.

**Comment by pguso** [comment]
The animateInView true is working if i test it with new browser versions (firefox/chrome). Can you explain in detail in wich case its not working?

**Comment by kylefraser** [comment]
Seems to be working just fine! Thanks!

**Comment by desiboli** [comment]
animateInView actually don't work on Safari, I use version 10.0.3. When I remove it, the circle animation works fine. Could someone confirm this, or am I doing something wrong ?
Example (not working in Safari):
`    $('#html-css-circle').circliful({
        animation: 1,
        animationStep: 2,
        animateInView: true,
        foregroundBorderWidth: 5,
        backgroundBorderWidth: 5,
        backgroundColor: '#28323A',
        percent: 83,
        textSize: 28,
        pointSize: 20,
        textStyle: 'font-size: 22px;',
        textColor: '#FFF',
        text: 'HTML & CSS',
        textBelow: true,
        multiPercentage: 1,
        percentages: [10, 20, 30],
        foregroundColor: '#DE3C4B'
    });`

**Comment by a1300206** [comment]
animateInView is not working on Chrome 62.0.3202.62, but nevertheless it's working on Safari, Chrome and even IE11.
Any solutions out there yet?

**Comment by marcsw2** [comment]
The culprit in Chrome seems to be line this line in jquery.circliful.js:

`var scrollElem = ((navigator.userAgent.toLowerCase().indexOf('webkit') != -1) ? 'body' : 'html');`

This passes "body" as the selector on the next line, i.e., `$("body").scrollTop();", which returns 0 in Chrome (at least in v. 61). If you just use "document" as the selector instead, things work as expected.

**Comment by a1300206** [comment]
Thanks marcsw2! Your solution is working like a charm.

**Comment by mariovelarde** [comment]
Hello I am new in this. So.... can you explain me how did you do?. Thanks so much.

**Comment by kimdah3** [comment]
For me the solution was to replace scrollElem with

`var scrollElem = ((navigator.userAgent.toLowerCase().indexOf('edge') != -1) ? 'body': 'html, body');`

It seems to be working on all browsers, not tested Safari yet.
