### ISSUE TITLE
Multiple bars

### ISSUE THREAD

**Issue by roccomuso** [pguso/jquery-plugin-circliful#124]
Is it possible to achieve something like this with this lib? having multiple bars..

![radial chart](http://www.datavizcatalogue.com/methods/images/top_images/radial_bar_chart.png)

**Comment by pguso** [comment]
Hey, not without changing the code.

**Comment by pguso** [comment]
Tried to implement multiple bars, you can test it here:

https://jsfiddle.net/0c8qaqaj/

If anybody has ideas on how to improve it your welcome!
