### ISSUE TITLE
Dimension (and responsive) not working

### ISSUE THREAD

**Issue by kshipp** [pguso/jquery-plugin-circliful#128]
Two bugs:
1)..Data-dimension is not working. It doesn't matter what value I place in there, nothing changes.  How do you fix the size of the circle?  You need to at least offer a MAX size, like every other.
2)..Responsive design isn't working either. It jumps all over the place in size and it almost always sizes OUTSIDE of it's parent container!!! Huge bug.

Nice start but these serious bugs keep me from using it.

**Comment by pguso** [comment]
1. there is no dimension parameter. You can see it when you go to the README file under Options, the max size is the outter container. In a bootstrap theme would you would place it like this: 

    <div class="col-lg-2">
            <div id="test-circle2"></div>
     </div>

2. Here is a demo online from the plugin http://gutersohn.com/circliful/demo.html and it works.

Maybe you use an old version of the plugin? the older version was written on html canvas and didn't supported responsive view, the new version is based on svg and support that.
