### ISSUE TITLE
Option for displaying rounded ends

### ISSUE THREAD

**Issue by pguso** [pguso/jquery-plugin-circliful#133]
https://stackoverflow.com/questions/37896870/need-help-for-linecaps

**Comment by philippeluickx** [comment]
I'm interested in this feature. Wondering why https://github.com/pguso/jquery-plugin-circliful/pull/65 didn't make it?

**Comment by philippeluickx** [comment]
Seems like https://github.com/realnickivanov/jquery-plugin-circliful/commit/17dfc124d8cc35e80d25504f2115f769ae40c8ba does the trick for me.
