### ISSUE TITLE
Chaining charts

### ISSUE THREAD

**Issue by 5ulo** [pguso/jquery-plugin-circliful#135]
I have 4 charts and I am looking for a solution how to chain chart animation. Example:
The charts are in view, the gray circle is present, first chart animates, runs callback, animates second > callback > third.. etc
I can run that but while first chart is loading (animating), second, third and fourth are blank, there's no gray circle. 
The question is, how to pre-generate circles (run charts) and wait until previosu chart has done the animation? Hint: `animationStep: 0` is pregenerating the circle without any animation.
Thanks
![circliful](https://user-images.githubusercontent.com/4980919/27155433-473a79bc-5159-11e7-9dbd-512b72428582.gif)

**Comment by pguso** [comment]
To do so a callback function is needed, i will think about a solution and implement it when i have some free time.

**Comment by rrd108** [comment]
It is answered here: https://github.com/pguso/jquery-plugin-circliful#use-callback-function
`$("#x1-circle").circliful({}, function(){
        $("#x2-circle").circliful();
    });`

**Comment by 5ulo** [comment]
@rrd108 it is not! That does exactly the same what you can see in the gif above

**Comment by rrd108** [comment]
@5ulo you are right, I skipped that part of your question.
Anyway what i would do is to present a placeholder image on start and hide it at the beginning of the callback.
