### ISSUE TITLE
Percents are not working correctly:

### ISSUE THREAD

**Issue by Dakado** [pguso/jquery-plugin-circliful#137]
When I manually specify percents it shows sometimes different values, for example I got 4 circles with these values:

percent: 95 - the circle shows 97%
percent: 1 - the circle shows 2%
percent: 44 - the circle shows 44%
percent: 100 - the circle shows 100%

So where is the problem ? These percent values are in the source of the actual page but the circles show different percetanges. Like 2 circles showing correct value and the other 2 dont ?

**Comment by howard60915** [comment]
May I ask what version of Circliful you are using?
I had the same problem when I used half-circle mode in previous version(1.0.2).
But I fixed it in #134 PR.
Pull the latest code and try it. Maybe everything will work fine. 
Hope this information help.

**Comment by Dakado** [comment]
Yes I use halfcircles I have just updated to the latest version and the bug is gone, thank you for helping me.
