### ISSUE TITLE
"undefined" present in generated SVG

### ISSUE THREAD

**Issue by simevo** [pguso/jquery-plugin-circliful#138]
If I look with the inspector at the generated DOM in the fiddle https://jsfiddle.net/9dajqcr1/:
```
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 194 186" class="circliful">undefined
  <circle cx="100" cy="100" r="57" class="border" fill="none" stroke="#ccc" stroke-width="15" stroke-dasharray="360" transform="rotate(-90,100,100)"></circle>
  <circle class="circle" cx="100" cy="100" r="57" fill="none" stroke="#3498DB" stroke-width="15" stroke-dasharray="136.8, 20000" transform="rotate(-90,100,100)"></circle>
  <circle cx="100" cy="100" r="28.5" fill="none"></circle>undefined
  <text class="timer" text-anchor="middle" x="100" y="110" style="font-size: 22px; undefined;" fill="#aaa">38%</text>
</svg>
```
the text "undefined" occurs twice around the `circle` elements and once in the style of the `text` element; if this markup is fed to a HTML5 linter such as https://html5.validator.nu/ it says:
```
"test.html":637.159-637.167: error: Text not allowed in element "svg" in this context.
"test.html":637.548-637.556: error: Text not allowed in element "svg" in this context.
```

**Comment by DC-development** [comment]
Hi @simevo , I just visited the linked fiddle and it looks alright to me? 
Im on a mbp 13", "high sierra" with latest chrome. If you don't insist I would suggest closing this bug or add more specs how to reproduce the Problem.

Cheers DC

**Comment by DC-development** [comment]
I do see those, too.

**Comment by simevo** [comment]
![immagine](https://user-images.githubusercontent.com/8254819/43099097-50300b76-8ec1-11e8-82d5-491431fc3e0b.png)

still there !
