### ISSUE TITLE
Half circle percentage progress bug

### ISSUE THREAD

**Issue by bajesus** [pguso/jquery-plugin-circliful#145]
It looks like this was fixed in the commit on Jun 12 but put back into the the master repo after that.  The percentage with the current commit has some kind of rounding error for half circles based off of what the animation steps are.  So 99 and 98 percent show as 100%. https://jsfiddle.net/cfyspqcg/

**Comment by mauroavello** [comment]
It also happens with a full circle, I get 101% when both values are the same.
Have you found how to solve it? Thanks

**Comment by mauroavello** [comment]
Reverted to 1.1.1 and working like you mentioned @bajesus. Thanks

**Comment by mlibre** [comment]
i fixed this bug by changing round to floor.
pull request address: https://github.com/pguso/jquery-plugin-circliful/pull/153
