### ISSUE TITLE
animateInView not working

### ISSUE THREAD

**Issue by kostasma** [pguso/jquery-plugin-circliful#148]
Hi i download the plugin. I made to the demo a small change , i add to a circle animateInView: true and in chrome not working but in firefox works fine

**Comment by pamcmelo** [comment]
Same situation here.

**Comment by lmonza** [comment]
I have the same problem... how can I solve this?

**Comment by dogusev** [comment]
```
function isElementInViewport() {
                var elementTop = circle.offset().top;
                var elementBottom = elementTop + circle.outerHeight();
                var viewportTop = $(window).scrollTop();
                var viewportBottom = viewportTop + $(window).height();
                
                return elementBottom > viewportTop && elementTop < viewportBottom;
            }
```

This should be the correct check.

**Comment by mfadeu** [comment]
Please prompt where to insert this code that check has earned?

**Comment by dogusev** [comment]
@mfadeu 
replace [this](https://github.com/pguso/jquery-plugin-circliful/blob/master/js/jquery.circliful.js#L319) method

**Comment by mfadeu** [comment]
Replace, but not work in my  code:

`$('.circle-animate').circliful({
				dimension: 90,
				width: 3,
				fontsize: 24,
				fgcolor: '#9AD551',
				bgcolor: '#F7F7F7',
				border: 'inline',
				animateInView: true,
				bordersize: 1}).each(function() {
					var $this = $(this),total = $this.attr('data-total'),
					part = $this.attr('data-part'),
					proc = part * 100 / total;
				});`

Animation starts during loading of the page...

What do I do not so?

**Comment by dogusev** [comment]
try with this param
```
  animation: 1,
  animateInView: true,
```


You can check the [sources, where this isElementInViewport  called from](https://github.com/pguso/jquery-plugin-circliful/blob/master/js/jquery.circliful.js#L178)
It firstly checks if the `animation` enabled

**Comment by melcu** [comment]
I try setting up: 
  animation: 1,
  animateInView: true,

No luck...

**Comment by tetsuobodyhammer** [comment]
This is STILL not working in iOS. iPhone 6 System 11.2.6, (Stock) Safari Browser. Real shame.

**Comment by pguso** [comment]
@tetsuobodyhammer your comment is not fair, i am now spending several years on this plugin i only got one donation over 3 dollar and not many contributed to this repo. but many are using it in templates for resale or productive websites. if you are not satisfied you can fix the bug and open a pull request or using another plugin offering what you need.

**Comment by tetsuobodyhammer** [comment]
Done. I will pay my developer to gut this thing, REBUILD IT, and get it working.

**Comment by pguso** [comment]
@melcu fixed please let me know if you still have some issues with that feature.
