### ISSUE TITLE
progressColor not working

### ISSUE THREAD

**Issue by OptimusPrimo11** [pguso/jquery-plugin-circliful#149]
Hi, I've updated the progressColor according to the line below, but fails. Am I missing something? Tried it in jsfiddle also no effect. Please help. Thanks.

$("#test-circle").circliful({
            animation: 1,
            animationStep: 5,
            foregroundBorderWidth: 15,
            backgroundBorderWidth: 15,
            percent: 75,
            textSize: 28,
            textStyle: 'font-size: 12px;',
            textColor: '#666',
            progressColor: { 50: '#152cc4', 60: '#FF6C00'},
            multiPercentage: 1,
            percentages: [10, 20, 30]
        });

**Comment by howard60915** [comment]
Since you set progressColor as  { 50: '#152cc4', 60: '#FF6C00'} which means circle color will change to #152cc4 when circle percentage reaches **50%** and change to  #FF6C00 when it reaches **60%**.

But your percentages array is set to [10, 20, 30], none of them reaches 50% or 60%.
Try to set higher number

**Comment by OptimusPrimo11** [comment]
Can you explain on this part? 

But your percentages array is set to [10, 20, 30]. What is the best range?

**Comment by howard60915** [comment]
You are using multiPercentage, so [10, 20, 30] means circliful will generate 3 circles for you.
The percentage of  3 circles  will be 10%, 20%, 30%
None of them are greater or equal to 50% or 60%, so the  circle color won't change 

Try to set progressColor as { 15: '#152cc4', 25: '#FF6C00'}
You will see the difference.

Btw, your **percentages** option format is wrong, check usage of  **Multiple Bar** on REAME document

**Comment by OptimusPrimo11** [comment]
Sorry for that. I'm actually trying to use only 1 bar. So I just removed that. Actually that is the original codes pasted in jsfiddle. 

https://jsfiddle.net/9dajqcr1/1530/

I just added the progressColor: { 50: '#152cc4', 60: '#FF6C00'}, and removed the percentages line. Still, no effect. Do you have any successful working samples that I can look at?

**Comment by howard60915** [comment]
I check your jsfiddle, its circliful.js version 1.0.2 which **multiPercentage and progressColor** are not available.

Check my jsfiiddle, I update circliful.js version to 1.2.0

https://jsfiddle.net/9dajqcr1/1535/

Hope it do help

**Comment by OptimusPrimo11** [comment]
Thanks !! I will try to update first.

**Comment by OptimusPrimo11** [comment]
Updated & tested. Works fine already, thanks for the help. Really appreciate !!
