### ISSUE TITLE
Allow Addition of text or Sign to the Percentage number

### ISSUE THREAD

**Issue by Abdulmanan0315** [pguso/jquery-plugin-circliful#156]
I am happily using this plugin but i want to have a bit more feature i want to show a text or an icon just before the percent number that animates.it should be of the same color & size as the percent number.
![capture](https://user-images.githubusercontent.com/20532497/43355183-7fd81ca2-9271-11e8-95e6-9d9a4e8a4144.PNG)
I will wait for this feature to be added soon so that i can use this on my project asap!
Thanks for the beautiful plugin.

**Comment by pguso** [comment]
@Abdulmanan0315 sorry for the late response, implemented your feature request. If there is still something missing for you, please reopen the ticket. Thank you
