### ISSUE TITLE
Half circle shows a wrong number

### ISSUE THREAD

**Issue by karstenpihl** [pguso/jquery-plugin-circliful#158]
When I'm using a half circle with `percent: 6` it shows `8%` for some reason, and I can't figure out why.

This is the configuration:
```
{
    animationStep: 5,
    foregroundBorderWidth: 5,
    backgroundBorderWidth: 15,
    percent: 6,
    halfCircle: 1
}
```
This is the result:
![image](https://user-images.githubusercontent.com/3703683/44260831-fbf5c100-a215-11e8-8ea8-f77fd7641580.png)

Se live example here: https://jsfiddle.net/9dajqcr1/4684/

**Comment by pguso** [comment]
@karstenpihl sorry for the very late response, its fixed in version 1.2.1, please use that - i updated your fiddle example to show that it works now as expected.
