### ISSUE TITLE
Percentage misaligned

### ISSUE THREAD

**Issue by invetico** [pguso/jquery-plugin-circliful#161]
Thank you for this wonderful plugin. I have a dialog box that open and inside it there is a circliful.

However, the percentage number that is meant to be shown in the middle is misaligned.

![image](https://user-images.githubusercontent.com/42125621/51167737-64e38100-18fb-11e9-8013-99c2321ad746.png)

Is there a way I could either recenter it or completely remove the percentage?

Thanks

**Comment by pguso** [comment]
@invetico i am very pleased to hear that. You could center it with css or use showPercent to hide it completely 

```
{
     percent: 80,
     showPercent: 0
}
```

**Comment by invetico** [comment]
I've put the showPercent to zero but it still shows the number

var TTCircle = $("#TTRequestCircle").circliful({
                    animationStep: 5,
                    foregroundBorderWidth: 5,
                    backgroundBorderWidth: 15,
                    percent: 75,
                    showPercent: 0
               });

![image](https://user-images.githubusercontent.com/42125621/51297211-86677880-1a73-11e9-93d8-00ed3644f52b.png)

**Comment by pguso** [comment]
Tested it on jsfiddle with latest version http://jsfiddle.net/qdLoxwbz/ and it works, if it still doesn't work for you. Please add an example on jsfiddle. Thank you
