### ISSUE TITLE
animationstep not recognized

### ISSUE THREAD

**Issue by lawsonculver** [pguso/jquery-plugin-circliful#17]
I've attempted to set animationstep="0" in the div tag, but it still animates.  It also appears to animate the same speed, regardless of the animationstep setting.

<div id="myStat" data-dimension="50" data-text="35%" data-percent="35" data-info="Percentage" data-width="5" data-fontsize="10" animationstep="0" data-fgcolor="##61a9dc" data-bgcolor="##eee" data-fill="##ddd" data-type="half"></div>

**Comment by SendDerek** [comment]
It appears the documentation is incorrect.  Looking at the code, it's expecting `data-animation-step`, *not* `data-animationstep`.

    if($(this).data('animation-step') != undefined) {
		animationstep = parseFloat($(this).data('animation-step'));
	} else {
		animationstep = settings.animationStep;
	}

I confirmed that changing the attribute to `data-animation-step` works.
