### ISSUE TITLE
browser compatibility

### ISSUE THREAD

**Issue by pcout** [pguso/jquery-plugin-circliful#4]
Hi,

What´s the browser compatibility list ?
Does it work in IE ?

Thanks

**Comment by paddotk** [comment]
@mehtabhaumik Thank you, Circliful didn't work in Safari but with that piece of code it does. Great! :D

**Comment by drewB** [comment]
For those looking to support ie8 with excanvas, in additional to the animation fix mentioned above (which you only need if you turn animation on), you also need to add the following line right before "var context = canvas.getContext('2d');":

            if (typeof(canvas.getContext) == "undefined" && typeof(G_vmlCanvasManager) != "undefined") {
                canvas = G_vmlCanvasManager.initElement(canvas)
            }
