### ISSUE TITLE
Filled Circle without overlapping border?

### ISSUE THREAD

**Issue by hamergil** [pguso/jquery-plugin-circliful#49]
Hi
Is it possible to get a filled circle and not having the border overlapping inside the filled area?
something like that:
http://i.imgur.com/3B36HDV.png
I couldn't see any option for that and don't understand why is it default like that.
thanks a lot

**Comment by paddotk** [comment]
Yes, you can use the `data-fill` (with your desired colour) and `data-bgcolor="transparent" properties  to achieve this.
