### ISSUE TITLE
late binding issues

### ISSUE THREAD

**Issue by cgiacomi** [pguso/jquery-plugin-circliful#52]
First of all thanks for the great work....

I am using AnglularJS and with the following example ( lots of attributes omitted for brevity)

    <div id="myStat" ...... data-text="{{scope_text_variable}}" 
        data-total="{{scope_total_variable}}" 
        data-part="{{scope_value_variable}}"></div>

The chart does not display the values as the chart is drawn before the scope variables are resolved.

Do you know a simple/elegant way to convert your pure jQuery library to a more AngularJS friendly one? 

Thank you in advance for the help

**Comment by pguso** [comment]
Can you try it again with the new plugin that is now based on svg?!
