### ISSUE TITLE
Data-bordersize don't work.

### ISSUE THREAD

**Issue by SlampD** [pguso/jquery-plugin-circliful#54]
Got these options: ` <div class="stat" id="myStat1" data-dimension="180" data-text="90" data-info="" data-width="15" data-bordersize="15" data-fontsize="50" data-percent="90" data-fgcolor="#3c989e" data-bgcolor="#eee" data-fill="white" data-total="100" data-part="90" data-icon="long-arrow-up" data-icon-size="28" data-icon-color="#fff" data-animationstep="0.4"></div> `

Bordersize didn't change.

**Comment by poyannabati** [comment]
For me as well.

**Comment by poyannabati** [comment]
Fix: On line 220 change 

`context.lineWidth = customSettingsObj.width + 1;`

to 

`context.lineWidth = customSettingsObj.bordersize + 1;`

**Comment by JSDesign** [comment]
@poyannabati outstanding - thanks for that!

**Comment by pguso** [comment]
@poyannabati thanks change the code.
