### ISSUE TITLE
Circliful not working withing an ng repeat

### ISSUE THREAD

**Issue by shyamg91** [pguso/jquery-plugin-circliful#55]
I'm trying to use circliful to create a bunch of graphs within an ng repeat. However it isn't working . Will circliful not work when used within an ng repeat. 

```
<div ng-repeat="type in types">
    <div>
        <div id="myStat" data-dimension="300" data-text="{{type.value}}" data-info="" data-type="half"    data-width="40" data-fontsize="38" data-percent="35" data-fgcolor="#61a9dc" data-bgcolor="#eee" data-fill="#fff" data-total="200" data-part="35" data-icon="long-arrow-up" data-icon-size="28" data-icon-color="#fff"></div>
    </div>
</div>
```

This is what my markup looks like. Any help or suggestions would be appreciated.

**Comment by pguso** [comment]
Can you try it again with the new plugin that is now based on svg?!

**Comment by marinabgarcia** [comment]
Try setTimeout it works for me but in Angular2.

 setTimeout(function(){
      $(".test-circle").circliful({
           animation: 1,
            animationStep: 6,
            foregroundBorderWidth: 5,
            backgroundBorderWidth: 1,
            percent: 88,
            iconColor: '#3498DB',
            icon: 'f004',
            iconSize: '40',
            iconPosition: 'middle'
});
},1000);
