### ISSUE TITLE
This chart not working in Widows Safari browser!

### ISSUE THREAD

**Issue by vpadhariya** [pguso/jquery-plugin-circliful#57]
this is a very good plugin and I had used in many of my projects.

some of my clients asked me that these charts are not working in Safari browser. So I would like to ask you that if any fixes for this are available.

Thanks for a good plugin.

I will be waiting for this.

**Comment by pguso** [comment]
With the aktual version of safari the plugin works fine, in which versions of safari your clients tested the plugin?

**Comment by vpadhariya** [comment]
Thanks, 

the version of safari browser is 5.1.7 in Windows

**Comment by pguso** [comment]
Changed the way the circle is drawing from canvas to svg. It should work now.
