### ISSUE TITLE
Pixelation after upgrading from 0.1.4 to 0.1.5

### ISSUE THREAD

**Issue by michaelthorne** [pguso/jquery-plugin-circliful#62]
Hey, neat plugin.

After using `0.1.4` on a project last year, I upgraded to `0.1.5` and noticed pixelation (jagged edges) on the foreground circle.

For the life of me, I cannot see what has changed from a canvas/drawing perspective.

I noticed there is now a `bgrCircle()` function which causes the undesirable rendering (compared to the previous version when all the drawing was inside `animate()`).

Any ideas?

### 0.1.4
![circliful-0 1 4](https://cloud.githubusercontent.com/assets/2629322/12548301/fe4c7a0a-c35d-11e5-8ae0-175044bd0f66.png)

### 0.1.5
![circliful-0 1 5](https://cloud.githubusercontent.com/assets/2629322/12548302/fe760dd4-c35d-11e5-8a5f-aa0a30b5d1a2.png)

**Comment by gautamz07** [comment]
@michaelthorne http://stackoverflow.com/questions/34987700/distorted-canvas-border-in-chrome-and-firefox. 

There is a bug in the source, you need to use clearRect() , if i have free time , i'll add the patch and update here :)

**Comment by michaelthorne** [comment]
@gautamz07 Thanks so much for the reply! And the link to a fix. :+1:

**Comment by michaelthorne** [comment]
@gautamz07 sorry about the commit + revert above, but I think I've fixed it. I wanted to create a separate pull request, but it included my previous fix #64 too.

Anyway, moving `bgrCircle()` in to `animate()` does the trick and gets rid of the distorting/pixelating.

**Comment by gautamz07** [comment]
@michaelthorne  no probs happy to help ;)
