### ISSUE TITLE
Always full circle

### ISSUE THREAD

**Issue by modbase** [pguso/jquery-plugin-circliful#63]
For some reason, my circles are always at 100%. This used to work, but is broken since the latest release (0.1.5)

![capture](https://cloud.githubusercontent.com/assets/1606383/12550163/32e9e0c8-c362-11e5-811d-b87ea1dacbe1.PNG)

`<div class="circliful" data-dimension="90" data-text="vCPUs" data-width="5" data-bordersize="3" data-fontsize="14" data-total="200" data-part="82" data-fgcolor="#5fbeaa" data-bgcolor="#ebeff2" style="width: 90px;"></div>`

`$('.circliful').circliful();`

Am I missing something?

**Comment by gautamz07** [comment]
where is you're data-percent ? see options https://github.com/pguso/jquery-plugin-circliful#data-options-attributes

**Comment by modbase** [comment]
Isn't that optional, because based on the documentation, the `data-total` and `data-part` will be used to calculate a percentage:

> If you want to display the percentage of a value for example you have 750MB Ram and at the moment are 350MB in use. You need to set data-total="750" and data-part="350" and the circle will show the percentage value 36,85%

Seems a bit odd that I have to manually calculate the percentage again then.

**Comment by gautamz07** [comment]
can you make a demo , because i've tested locally and it works just fine :)

**Comment by modbase** [comment]
Here's a demo: http://jsfiddle.net/sk8fxcqb/

**Comment by gautamz07** [comment]
@modbase  somehow the CDN you're using seems to be outdated , infact if you check the source of the CDN , it has no code that calculates data-part and data-total , use https://github.com/pguso/jquery-plugin-circliful/blob/master/js/jquery.circliful.js , its the latest and works fine, for your use case. 

http://jsfiddle.net/sk8fxcqb/3/

**Comment by modbase** [comment]
Using the master version indeed fixes the issue. I used version 0.1.5.
