### ISSUE TITLE
0.1.6 tagged release has incorrect bower.json version (0.1.5)

### ISSUE THREAD

**Issue by ericbarch** [pguso/jquery-plugin-circliful#68]
Just noticed bower was failing to resolve this dependency. Looks like it was finding the 0.1.6 tagged release and crashing out once it read the bower.json.

`mismatch Version declared in the json (0.1.5) is different than the resolved one (0.1.6)`

Seems a few of my other dependencies have this issue too and seem to resolve, though. *shrug*

**Comment by pguso** [comment]
solved
