### ISSUE TITLE
Circle charts broken

### ISSUE THREAD

**Issue by ztoliver** [pguso/jquery-plugin-circliful#71]
I was using the most recent version which included an update to include text instead of icons below the percentage. All was well with that. All of the charts on my site broke with the recent renaming of the files. I updated the css and js cdn paths, but now be charts will not initialize.

Using:
`<link href="https://cdn.rawgit.com/pguso/jquery-plugin-circliful/master/css/jquery.circliful.css" rel="stylesheet">`
`<script src="https://cdn.rawgit.com/pguso/jquery-plugin-circliful/master/js/jquery.circliful.min.js"></script>   `

To test, I have an element called "test-chart".
`<div id="test-chart"></div>`

I am initializing on document load with:
`    $("#test-chart").circliful({
        animationStep: 5,
        foregroundBorderWidth: 15,
        backgroundBorderWidth: 15,
        percent: 20,
        foregroundColor: "#4caf50",
        text: "CPU"
    });
`

All I see is an empty chart with a gray outer border, none of the settings above applied.

![image](https://cloud.githubusercontent.com/assets/8801099/13343912/d4c9eae2-dc16-11e5-93d5-d3e91f137f1f.png)

Same thing happens in jsfiddle:
[https://jsfiddle.net/k1sfd7rt/]

**Comment by pguso** [comment]
This is because the cdn still has the "old" version of circliful cached and the parameters where renamed so the old version doesnt recognize your params.

Visit https://rawgit.com/faq#cdn-ttl for more details.
