### ISSUE TITLE
0.1.5 to 0.1.6 is not a minor release

### ISSUE THREAD

**Issue by timbofield** [pguso/jquery-plugin-circliful#75]
You need to bump the version number way higher, make 0.1.6 = 1.0.0 or something as this doesn't seem to be a minor release at all. Everyone who has this in a bower.json or similar is going to get there sites broken. 

Thanks for the plugin.

**Comment by pguso** [comment]
Thanks for the info, i changed it...

**Comment by gautamz07** [comment]
http://semver.org/
