### ISSUE TITLE
Function call on complete

### ISSUE THREAD

**Issue by paddotk** [pguso/jquery-plugin-circliful#78]
Hi,
Is it possible to do have a function fired once the animation completes? I can't find such an option in the readme.
If not, would you consider adding such a function?
Love you.

**Comment by gautamz07** [comment]
@paddotk somebody seems to have goofed up with the code , you can add your call back code when initiating the plugin like so:

```
$("#circli").circliful({
            animation: 1,
            animationStep: 10,
            foregroundBorderWidth: 5,
            backgroundColor: "none",
            fillColor: '#eee',
            percent: 75,
            iconColor: '#3498DB',
            icon: 'f206',
            iconSize: '40',
            iconPosition: 'middle',
            start:50,
            showPercent:1,
            target:0
        }, function(){
            alert('done !');
        });
```

and then edit the source code of the plugin at [this point](https://github.com/pguso/jquery-plugin-circliful/blob/master/js/jquery.circliful.js#L139) , just add the below line of code:

`callback();`

so the code now inside the if condition will look like:

```
window.clearInterval(timer);
last = 1;
callback();
```
