### ISSUE TITLE
half round chart is missing in new version 1.0.0

### ISSUE THREAD

**Issue by RabbitJImmy** [pguso/jquery-plugin-circliful#79]
I find this plugin, and it looks cool, The very amazing thing is the half round chart, because it takes less space, and easy to put it in a line of data grid. But in version 1.0 data-type="half" won't work. and there's no logic found in circleful.js. and all the attributes set in div won't work for this circleful plugin. All you need to set must be in javascript. 

is there any way to use the half round chart? 
or this will be added in the next version？

thanks

I really like this

cheers

**Comment by giovannimanzoni** [comment]
look at my fork :) https://github.com/pguso/jquery-plugin-circliful/pull/85
