### ISSUE TITLE
Internet explorer 11

### ISSUE THREAD

**Issue by angeand** [pguso/jquery-plugin-circliful#82]
Hi,
I'm trying to use it on all last browser. On internet Explorer 11 the last release draws litle circles, on others browser the dimensions are right. I have tried with class 'container', class 'row'  and class 'col-lg-2' and I have tried also with tag 'table' but the result is always the same: litle circle on IE 11 and right dimensions on other browser (Chrome, Firefox  and Edge).
Is there someone with the same problem ?

Best regards
Andrea

**Comment by gautamz07** [comment]
Can you show us some code ? a [Fiddle](https://jsfiddle.net/) or a live demo , its hard to tell without any code

**Comment by mmisur** [comment]
Having the same issue

**Comment by DC-development** [comment]
The SVG doesn't really have "size" for it is vectorized grafics. If you resize the parent the SVG will grow and shrink corresponding to its parent container.

I think this is more of a css problem?
