### ISSUE TITLE
Only showing 75%

### ISSUE THREAD

**Issue by KratosMafia** [pguso/jquery-plugin-circliful#83]
So starting today for some reason they ONLY show 75%. All was working for past few months then today BAM. It just broke. I didn't change anything at all. I am trying to fix but I see no issue.

If you look here
http://blog.web68.vn/en/circular-statistic-indicator-with-circliful-jquery-plugin-591.html

You can see even on their page that everything shows 75%.

**Comment by achilleas22** [comment]
I have the same problem. Does anybody know what is wrong?

**Comment by pandalowry** [comment]
data-text not works for me later, and same problem. 75% only.
please help ) 
I understand - update you software. And we must download previous state commit's repo.
But, what commit?

**Comment by leonliusha** [comment]
Still only 75%.

**Comment by deanc** [comment]
Confirmed same issue here with vanilla version from master

**Comment by hsevilla** [comment]
You guys are using the new version of the plugin and the specs are not the same, to set the value of a circle you need to specify it via javascript, not with data value on html.

`<script>
$( document ).ready(function() {
        $("#your-circle").circliful({
        animationStep: 5,
        foregroundBorderWidth: 5,
        backgroundBorderWidth: 15,
        percent: 75
    });
    });
</script>`

Example: [http://codepen.io/barcadictni/pen/jAKoJB](http://codepen.io/barcadictni/pen/jAKoJB)

**Comment by NioTeX** [comment]
Is there no way to specify options vie html data anymore?

**Comment by caligan** [comment]
For anyone else who needs a solution using data attributes, I went this route:

  targets = jQuery(".selector");
  jQuery.each(targets, function(key, value) {
    target = jQuery(value);
    var percent = target.data('width');
    target.circliful({
      animationStep: 5,
      foregroundBorderWidth: 5,
      backgroundBorderWidth: 15,
      percent: percent
    });
  });
