### ISSUE TITLE
Different text

### ISSUE THREAD

**Issue by JerryLosey** [pguso/jquery-plugin-circliful#84]
Is it possible to change the main text inside the circles?  Let's say I want to display "19/24" and then set the percentage separately.

**Comment by ghermans** [comment]
any update regarding this?

**Comment by bjankord** [comment]
I'd be willing to submit a PR if @pguso is open to the idea.

**Comment by ghermans** [comment]
@bjankord i can't speak for @pguso, however for myself i'm looking forward to your PR.
Thanks in advance.

**Comment by pguso** [comment]
@bjankord i am open for every PR, so please implement your changes and send a PR, i will review it quickly

**Comment by ghermans** [comment]
@bjankord do you have any updates regarding this?

**Comment by pguso** [comment]
Added a new parameter for this "replacePercentageByText". You can use it like this...

    $("#test-circle").circliful({
            animation: 1,
            animationStep: 5,
            foregroundBorderWidth: 15,
            backgroundBorderWidth: 15,
            percent: 20,
            textSize: 28,
            textStyle: 'font-size: 12px;',
            textColor: '#666',
            replacePercentageByText: '19/24'
        });
