### ISSUE TITLE
Remove body styles from CSS

### ISSUE THREAD

**Issue by toovy** [pguso/jquery-plugin-circliful#87]
I think the circliful.css should not add any property to the body:

```
body {
    background-color: #fff;
    color: #333;
    font-family: 'Lato', sans-serif;
}
```

In my opinion this should be removed. It killed my font-family settings.

**Comment by perttumyry** [comment]
Yup, we cannot use this in our project because of fiddling with body styles. In addition, importing Lato from Google fonts is useless traffic for us as we don't use it. Going to test Chart.js instead, but I'd be happy to test Circliful again once it matures bit further.

**Comment by perttumyry** [comment]
Nice, thanks @pguso for quick action.

**Comment by toovy** [comment]
@pguso thanks!
