### ISSUE TITLE
Uncaught TypeError $(...).circliful is not a function when inside another function

### ISSUE THREAD

**Issue by leofontes** [pguso/jquery-plugin-circliful#89]
Hey all,

First of all, I have Circliful installed correctly because it works on some situations, just to get this out of the way.
On my app, when I call the circliful function with the settings like this:
```
$(document).ready(function() {
    $("someSelector").circliful();
}
```

It works and displays the circle I want (I also add settings, but this is not the point).

However, if I try to call circliful inside an AJAX request or a click event, **starting a circle OR after having destroyed an existing one** like this for example: 

```
$(document).ready(function() {
   $.ajax({
		method: 'GET',
		dataType: 'json',
		url: '/something',
		success: function(data) {
			$('someSelector').circliful();
		}
	});

   //Or
   $('#someButton').click(function() {
      $('someSelector').circliful();
   }
}
```

It gives me the error:

Uncaught TypeError: $(...).circliful is not a function

For the record I tried some of the solutions on the issues page here but nothing worked. Thank you

**Comment by gautamz07** [comment]
Works  perfectly fine with Ajax and also inside a click event see here https://jsfiddle.net/p14aqasc/1/
