### ISSUE TITLE
Over 100 percent

### ISSUE THREAD

**Issue by hsevilla** [pguso/jquery-plugin-circliful#92]
Hi, is it possible to add a circle with a percent over than 100%?, for example 120%, could be with an inner circle with other color.

![screenshot at jul 14 21-28-52](https://cloud.githubusercontent.com/assets/20289065/16862809/0f8eaff8-4a0a-11e6-857c-6763fc5b47a2.png)

**Comment by hsevilla** [comment]
@pguso

**Comment by pguso** [comment]
Not yet but it would be great to implement this!
