### ISSUE TITLE
Remove percentage sign

### ISSUE THREAD

**Issue by flexbrane** [pguso/jquery-plugin-circliful#94]
Hello!

I would like to remove the pourcentage sign, is it possible ?

For exemple, this : 
![image](https://cloud.githubusercontent.com/assets/14235706/17219422/a0bc9fd0-54eb-11e6-8d57-e8faa1418caf.png)

To this :
![image](https://cloud.githubusercontent.com/assets/14235706/17219406/8ed674d0-54eb-11e6-88a9-c2c621ce8d6f.png)

Thank you.

**Comment by pguso** [comment]
Now you have a new parameter "noPercentageSign" if you set it to true you can hide the percentage sign. For example:

    $("#test-circle5").circliful({
            animationStep: 5,
            foregroundBorderWidth: 5,
            backgroundBorderWidth: 15,
            percent: 80,            
            icon: 'f0a0',
            iconPosition: 'middle',
            text: 'Space Left',            
            textBelow: true,
            noPercentageSign: true
        });
